site_name: Библиография исторического танца
docs_dir: docs
site_dir: ./www/static/docs
nav:
  - index.md
  - Общая информация:
    - Лицензия: common/license.md
    - Теги: common/tags.md
    - Библиотеки: common/libraries.md
  - Библиография:
    - Общая информация: bib/index.md
    - Периодика: bib/periodical.md
    - Библиотека HDA: bib/library.md
    - Отсутствующие записи: bib/missing.md
    - Транскрипции: bib/transcriptions.md
    - Издания Пабло Минге-и-Ироля: bib/yrol.md
  - Иконография: images.md
  - Музыка:
    - Устройство архива с музыкой: music.md
    - Альбомы для исторических танцев: music_cds.md
  - Резервные копии: backups.md
plugins: []
theme:
  name: mkdocs
  nav_style: dark
strict: true
